# Generated by Django 4.2.14 on 2024-12-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdfs',
        ),
    ]
